name: basic-ci

on: [push]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: set-up
        id: go
        users: actions/setup-go@v3
        with:
          go-version: ^1.18
      - name: checkout
        uses: actions/checkout@v3
